interface CityWeather {
  location: string;
  temperature: number;
  condition: string;
  feelsLike: number;
  forecast: { high: number; low: number };
  wind: { speed: number; direction: string };
  pressure: number;
  humidity: number;
  dewPoint: number;
}

const weatherByCity: Record<string, CityWeather> = {
  'Da Nang': {
    location: 'Da Nang Airport',
    temperature: 23,
    condition: 'Passing clouds',
    feelsLike: 22,
    forecast: { high: 26, low: 22 },
    wind: { speed: 4, direction: 'North' },
    pressure: 1013,
    humidity: 89,
    dewPoint: 21,
  },
  'Ho Chi Minh City': {
    location: 'Tan Son Nhat Airport',
    temperature: 26,
    condition: 'Sunny',
    feelsLike: 28,
    forecast: { high: 30, low: 24 },
    wind: { speed: 3, direction: 'East' },
    pressure: 1010,
    humidity: 72,
    dewPoint: 19,
  },
  'Hanoi': {
    location: 'Noi Bai Airport',
    temperature: 15,
    condition: 'Cloudy',
    feelsLike: 13,
    forecast: { high: 18, low: 12 },
    wind: { speed: 5, direction: 'Northwest' },
    pressure: 1015,
    humidity: 78,
    dewPoint: 10,
  },
  'Ha Long': {
    location: 'Ha Long Bay',
    temperature: 18,
    condition: 'Partly Cloudy',
    feelsLike: 17,
    forecast: { high: 22, low: 16 },
    wind: { speed: 6, direction: 'Northeast' },
    pressure: 1012,
    humidity: 82,
    dewPoint: 14,
  },
  'Hue': {
    location: 'Phu Bai Airport',
    temperature: 20,
    condition: 'Light Rain',
    feelsLike: 19,
    forecast: { high: 24, low: 18 },
    wind: { speed: 7, direction: 'East' },
    pressure: 1011,
    humidity: 85,
    dewPoint: 16,
  },
  'Da Lat': {
    location: 'Da Lat City',
    temperature: 12,
    condition: 'Clear',
    feelsLike: 11,
    forecast: { high: 18, low: 10 },
    wind: { speed: 2, direction: 'South' },
    pressure: 920,
    humidity: 65,
    dewPoint: 5,
  },
  'Nha Trang': {
    location: 'Nha Trang Bay',
    temperature: 25,
    condition: 'Sunny',
    feelsLike: 26,
    forecast: { high: 28, low: 23 },
    wind: { speed: 3, direction: 'Southeast' },
    pressure: 1012,
    humidity: 75,
    dewPoint: 20,
  },
  'Can Tho': {
    location: 'Can Tho City',
    temperature: 27,
    condition: 'Hot & Humid',
    feelsLike: 30,
    forecast: { high: 31, low: 25 },
    wind: { speed: 2, direction: 'Southwest' },
    pressure: 1009,
    humidity: 80,
    dewPoint: 22,
  },
  'Bangkok': {
    location: 'Suvarnabhumi Airport',
    temperature: 28,
    condition: 'Thunderstorm',
    feelsLike: 32,
    forecast: { high: 32, low: 26 },
    wind: { speed: 8, direction: 'Southwest' },
    pressure: 1008,
    humidity: 85,
    dewPoint: 24,
  },
  'Chiang Mai': {
    location: 'Chiang Mai City',
    temperature: 22,
    condition: 'Haze',
    feelsLike: 21,
    forecast: { high: 26, low: 18 },
    wind: { speed: 3, direction: 'North' },
    pressure: 1011,
    humidity: 68,
    dewPoint: 14,
  },
  'Phuket': {
    location: 'Phuket International',
    temperature: 26,
    condition: 'Partly Cloudy',
    feelsLike: 28,
    forecast: { high: 30, low: 24 },
    wind: { speed: 5, direction: 'Southwest' },
    pressure: 1010,
    humidity: 78,
    dewPoint: 21,
  },
  'Singapore': {
    location: 'Changi Airport',
    temperature: 27,
    condition: 'Rainy',
    feelsLike: 32,
    forecast: { high: 31, low: 26 },
    wind: { speed: 4, direction: 'North' },
    pressure: 1012,
    humidity: 82,
    dewPoint: 23,
  },
  'Kuala Lumpur': {
    location: 'Kuala Lumpur International',
    temperature: 28,
    condition: 'Humid',
    feelsLike: 32,
    forecast: { high: 32, low: 25 },
    wind: { speed: 3, direction: 'East' },
    pressure: 1010,
    humidity: 80,
    dewPoint: 23,
  },
  'Jakarta': {
    location: 'Soekarno-Hatta Airport',
    temperature: 27,
    condition: 'Cloudy',
    feelsLike: 30,
    forecast: { high: 31, low: 25 },
    wind: { speed: 4, direction: 'West' },
    pressure: 1009,
    humidity: 78,
    dewPoint: 21,
  },
  'Bali': {
    location: 'Ngurah Rai Airport',
    temperature: 26,
    condition: 'Sunny',
    feelsLike: 28,
    forecast: { high: 30, low: 24 },
    wind: { speed: 5, direction: 'Southeast' },
    pressure: 1011,
    humidity: 75,
    dewPoint: 20,
  },
  'Manila': {
    location: 'Ninoy Aquino Airport',
    temperature: 29,
    condition: 'Hot',
    feelsLike: 33,
    forecast: { high: 33, low: 27 },
    wind: { speed: 3, direction: 'West' },
    pressure: 1009,
    humidity: 72,
    dewPoint: 22,
  },
  'Cebu': {
    location: 'Mactan Airport',
    temperature: 28,
    condition: 'Sunny',
    feelsLike: 30,
    forecast: { high: 32, low: 26 },
    wind: { speed: 4, direction: 'East' },
    pressure: 1011,
    humidity: 70,
    dewPoint: 21,
  },
  'Hong Kong': {
    location: 'Hong Kong International',
    temperature: 17,
    condition: 'Cloudy',
    feelsLike: 15,
    forecast: { high: 20, low: 15 },
    wind: { speed: 6, direction: 'Northeast' },
    pressure: 1014,
    humidity: 72,
    dewPoint: 11,
  },
  'Shanghai': {
    location: 'Pudong International',
    temperature: 12,
    condition: 'Clear',
    feelsLike: 10,
    forecast: { high: 16, low: 9 },
    wind: { speed: 4, direction: 'North' },
    pressure: 1016,
    humidity: 65,
    dewPoint: 3,
  },
  'Beijing': {
    location: 'Capital International',
    temperature: 8,
    condition: 'Haze',
    feelsLike: 5,
    forecast: { high: 12, low: 4 },
    wind: { speed: 5, direction: 'Northwest' },
    pressure: 1018,
    humidity: 60,
    dewPoint: -2,
  },
  'Tokyo': {
    location: 'Narita International',
    temperature: 10,
    condition: 'Clear',
    feelsLike: 8,
    forecast: { high: 14, low: 7 },
    wind: { speed: 3, direction: 'North' },
    pressure: 1017,
    humidity: 58,
    dewPoint: 0,
  },
  'Seoul': {
    location: 'Incheon International',
    temperature: 5,
    condition: 'Cloudy',
    feelsLike: 2,
    forecast: { high: 10, low: 2 },
    wind: { speed: 4, direction: 'Northwest' },
    pressure: 1019,
    humidity: 65,
    dewPoint: -3,
  },
  'Taipei': {
    location: 'Taiwan Taoyuan',
    temperature: 18,
    condition: 'Partly Cloudy',
    feelsLike: 17,
    forecast: { high: 22, low: 15 },
    wind: { speed: 5, direction: 'East' },
    pressure: 1013,
    humidity: 70,
    dewPoint: 11,
  },
  'Sydney': {
    location: 'Sydney Kingsford',
    temperature: 22,
    condition: 'Sunny',
    feelsLike: 21,
    forecast: { high: 25, low: 19 },
    wind: { speed: 4, direction: 'South' },
    pressure: 1015,
    humidity: 62,
    dewPoint: 13,
  },
  'Melbourne': {
    location: 'Melbourne Tullamarine',
    temperature: 18,
    condition: 'Cloudy',
    feelsLike: 16,
    forecast: { high: 22, low: 15 },
    wind: { speed: 5, direction: 'West' },
    pressure: 1013,
    humidity: 68,
    dewPoint: 10,
  },
  'Auckland': {
    location: 'Auckland International',
    temperature: 16,
    condition: 'Rainy',
    feelsLike: 14,
    forecast: { high: 19, low: 13 },
    wind: { speed: 7, direction: 'Southwest' },
    pressure: 1011,
    humidity: 75,
    dewPoint: 11,
  },
  'New York': {
    location: 'JFK International',
    temperature: 5,
    condition: 'Clear',
    feelsLike: 1,
    forecast: { high: 10, low: 2 },
    wind: { speed: 8, direction: 'Northwest' },
    pressure: 1020,
    humidity: 55,
    dewPoint: -4,
  },
  'Los Angeles': {
    location: 'LAX International',
    temperature: 22,
    condition: 'Sunny',
    feelsLike: 21,
    forecast: { high: 26, low: 18 },
    wind: { speed: 3, direction: 'West' },
    pressure: 1013,
    humidity: 45,
    dewPoint: 8,
  },
  'London': {
    location: 'Gatwick Airport',
    temperature: 8,
    condition: 'Rainy',
    feelsLike: 5,
    forecast: { high: 12, low: 5 },
    wind: { speed: 6, direction: 'Southwest' },
    pressure: 1012,
    humidity: 75,
    dewPoint: 4,
  },
  'Paris': {
    location: 'Charles de Gaulle',
    temperature: 10,
    condition: 'Cloudy',
    feelsLike: 8,
    forecast: { high: 14, low: 6 },
    wind: { speed: 4, direction: 'West' },
    pressure: 1014,
    humidity: 70,
    dewPoint: 4,
  },
  'Berlin': {
    location: 'Berlin Tegel',
    temperature: 7,
    condition: 'Overcast',
    feelsLike: 5,
    forecast: { high: 11, low: 4 },
    wind: { speed: 5, direction: 'North' },
    pressure: 1015,
    humidity: 68,
    dewPoint: 0,
  },
  'Dubai': {
    location: 'Dubai International',
    temperature: 32,
    condition: 'Clear',
    feelsLike: 35,
    forecast: { high: 36, low: 28 },
    wind: { speed: 2, direction: 'East' },
    pressure: 1008,
    humidity: 35,
    dewPoint: 14,
  },
  'Mumbai': {
    location: 'Indira Gandhi Airport',
    temperature: 28,
    condition: 'Partly Cloudy',
    feelsLike: 32,
    forecast: { high: 32, low: 25 },
    wind: { speed: 5, direction: 'West' },
    pressure: 1009,
    humidity: 75,
    dewPoint: 22,
  },
  'Delhi': {
    location: 'Indira Gandhi New',
    temperature: 15,
    condition: 'Haze',
    feelsLike: 13,
    forecast: { high: 20, low: 10 },
    wind: { speed: 3, direction: 'East' },
    pressure: 1016,
    humidity: 70,
    dewPoint: 8,
  },
  'Cairo': {
    location: 'Cairo International',
    temperature: 24,
    condition: 'Clear',
    feelsLike: 23,
    forecast: { high: 28, low: 20 },
    wind: { speed: 4, direction: 'North' },
    pressure: 1013,
    humidity: 45,
    dewPoint: 11,
  },
};

export function getWeatherByCity(city: string): CityWeather {
  return weatherByCity[city] || weatherByCity['Da Nang'];
}
